name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and test on .NET Core
  dotnet-core-ci:
    name: .NET Core CI - test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Force use of specific version until https://github.com/dotnet/format/issues/1500 is fixed
        dotnet-version: ['6.0.100']
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build

      - name: Run tests
        run: dotnet test

      - name: Run linter
        run: dotnet format --verify-no-changes

  # Build and test on .NET Framework
  dotnet-framework-ci:
    name: .NET Framework CI - test
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

      - name: Set up NuGet
        uses: NuGet/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0

      - name: Set up VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Install dependencies
        run: nuget restore duo_universal_csharp.sln

      - name: Build solution
        run: msbuild.exe duo_universal_csharp.sln

      - name: Run DuoUniversal.Tests
        run: vstest.console.exe .\DuoUniversal.Tests\bin\Debug\net6.0\DuoUniversal.Tests.dll

