---
name: Build and Sign a release

on:
  workflow_dispatch:

permissions: {}

jobs:
  package:
    runs-on: windows-2022
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "6.0.100"

      - name: Create NuGet package
        run: dotnet pack -c Release -o ../out
        working-directory: DuoUniversal

      - name: Artifact the .nupkg
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: nupkg
          path: out/DuoUniversal*.nupkg
          retention-days: 1

  sign:
    runs-on: windows-2022
    environment: authenticode-signing
    needs: package
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 11

      # NuGet doesn't support signature via signtool.exe, instead using
      # nuget sign or dotnet nuget sign. These commands do not support
      # detached signing. So, we have to use a different tool, jsign.
      - name: Install jsign
        run: choco install --ignore-dependencies jsign

      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: nupkg

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ secrets.AUTHENTICODE_ROLE_ARN }}
          role-session-name: jsign-kms
          aws-region: us-west-2


      - name: Stage authenticode public certificate
        run: |
          # Pull a configured certificate parameter and write it to a specified location
          $b64 = aws ssm get-parameter `
          --name $env:AUTHENTICODE_CERTIFICATE_PARAMETER `
          --with-decryption `
          --query "Parameter.Value" `
          --output text
          $bytes = [Convert]::FromBase64String($b64)
          [IO.File]::WriteAllBytes($env:CERT_FILE, $bytes)
          [System.Security.Cryptography.X509Certificates.X509Certificate2]::CreateFromCertFile($env:CERT_FILE) | Select-Object "*"
        env:
          AUTHENTICODE_CERTIFICATE_PARAMETER: ${{ secrets.AUTHENTICODE_CERTIFICATE_PARAMETER }}
          CERT_FILE: authenticode.cer

      - name: Sign nupkg
        shell: cmd
        run: jsign --tsaurl http://timestamp.digicert.com --tsmode RFC3161 --storetype AWS --keystore us-west-2 --alias %KEY_ID% --certfile %CERT_FILE% DuoUniversal*.nupkg
        env:
          CERT_FILE: authenticode.cer
          KEY_ID: ${{ secrets.AUTHENTICODE_KMS_KEY_ID }}

      - name: Retain signed binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: |
            authenticode.cer
            DuoUniversal*.nupkg
          retention-days: 1
